import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appName: 'MediAssist AI',
    dashboard: 'Dashboard',
    myRecords: 'My Records',
    symptomChecker: 'Symptom Checker',
    reportAnalyzer: 'Report Analyzer',
    imageAnalysis: 'Image Analysis',
    chat: 'AI Chat',
    emergency: 'Emergency',
    settings: 'Settings',
    disclaimer: 'MediAssist AI is not a substitute for professional medical advice. Always consult a licensed healthcare provider.',
    disclaimer_short: 'AI analysis only — not a diagnosis',
    heroTitle: 'Intelligent Healthcare Assistant',
    heroSubtitle: 'Get instant insights on symptoms, medical reports, and health questions — powered by advanced AI.',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    patientsAssisted: 'Patients Assisted',
    reportsAnalyzed: 'Reports Analyzed',
    aiAccuracy: 'AI Triage Accuracy',
    languagesSupported: 'Languages Supported',
    symptomCheckerTitle: 'AI Symptom Checker',
    symptomCheckerDesc: 'Provide current symptoms to check severity levels, risk assessment, and details.',
    reportAnalyzerTitle: 'Report Analyzer',
    reportAnalyzerDesc: 'Upload blood panels or other medical reports. AI simplifies complex medical jargon.',
    imageAnalysisTitle: 'Image Analyzer',
    imageAnalysisDesc: 'Upload photos of skin conditions or scans for initial visual triage.',
    chatTitle: 'Health Chatbot',
    chatDesc: 'Ask health-related questions, request diet suggestions, or look up drug precautions.',
    symptomCheckerHeading: 'AI Symptom Assessment',
    symptomCheckerSub: 'State your health observations clearly. The AI checks for clinical parameters, alerts emergency triggers, and calculates severity levels.',
    describeSymptomsPlaceholder: 'Describe your symptoms (e.g. Mild headache, coughing, fever since yesterday)...',
    analyzeSymptomsButton: 'Analyze Symptoms',
    evaluatingSymptoms: 'Evaluating symptoms. Cross-referencing clinical database...',
    indicatedCondition: 'Indicated Condition',
    clinicalExplanation: 'Clinical Explanation',
    suggestedActions: 'Suggested Actions',
    downloadPDF: 'Download PDF',
    noAnalysisYet: 'No Analysis Yet',
    noAnalysisYetDesc: 'Fill in your symptoms and click analyze to start generating assessment reports.',
    reportAnalyzerHeading: 'Medical Report Explainer',
    reportAnalyzerSub: 'Upload lab reports, CBC, thyroid tests, or other health sheets. AI processes fields and details abnormal findings.',
    dragDropPlaceholder: 'Drag & drop files here, or click to browse (PDF, Images)',
    ocrScanning: 'Processing file. Extracting biomarkers and ranges...',
    parametersExtracted: 'Key parameters extracted',
    simplifiedTranslation: 'Simplified Translation',
    lifestyleAdvice: 'Lifestyle & Nutritional Advice',
    tableParameter: 'Parameter',
    tableValue: 'Value',
    tableNormal: 'Normal Range',
    tableStatus: 'Status',
    uploadReportButton: 'Upload Report',
    waitingForUpload: 'Awaiting Document',
    waitingForUploadDesc: 'Upload a PDF or scan to automatically view structured summaries and warnings.',
    documentParsed: 'Document Parsed Successfully',
    imageAnalysisHeading: 'Visual Diagnostics',
    imageAnalysisSub: 'Upload photos of skin irritation, rashes, or scans. The AI detects surface irregularities and calculates confidence metrics.',
    visualScanCompleted: 'Visual Scan Completed',
    confidenceScore: 'AI Model Confidence Score',
    visualObservations: 'Visual Observations',
    suggestionsActions: 'Suggested Actions & Checks',
    caveat: 'Visual check only — not an oncology or medical diagnostic screening.',
    clearFile: 'Clear File',
    reAnalyze: 'Re-Analyze Image',
    awaitingPhoto: 'Awaiting Medical Photo',
    awaitingPhotoDesc: 'Upload a skin photo or scan to review confidence scores, visual findings, and alerts.',
    chatHeading: 'Clinical Chat Companion',
    chatSub: 'Ask general questions about lifestyle, nutritional tips, exercise, or common medication instructions.',
    suggestedQuestions: 'Suggested Questions',
    typeMessagePlaceholder: 'Ask a health or wellness question...',
    sendButton: 'Send',
    typingIndicator: 'Evaluating query and compiling clinical guidelines...',
    emergencyWarning: '🚨 EMERGENCY WARNING: High severity symptoms detected. Contact emergency response immediately.',
    dashboardHeading: 'Health Command Dashboard',
    dashboardSub: 'Monitor vitals, review previous consultations, and receive AI health tips.',
    activeMinutes: 'Active Minutes',
    heartRate: 'Heart Rate',
    healthScore: 'Health Index Score',
    riskStatus: 'Systemic Risk Status',
    recentActivity: 'Recent Activity',
    recentActivityDesc: 'Recent health check-ups and diagnostic scans.',
    vitalTracker: 'Activity & Vitals Tracker',
    activityLog: 'Consultations & Activity Log',
    noConsultations: 'No consultations registered yet.',
    aiHealthTipTitle: 'AI Health Insight & Recommendations',
    quickActions: 'Quick Diagnostic Tools',
    emergencyHeading: 'Emergency Assistance',
    emergencySub: 'If you are experiencing chest pain, severe breathing difficulty, or heavy bleeding, call local emergency services immediately.',
    emergencyCall: 'Call Emergency Hotline',
    emergencyContacts: 'Emergency Contacts',
    loginHeading: 'Welcome Back',
    loginSub: 'Sign in to your MediAssist AI health companion',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    signInButton: 'Sign In',
    signingIn: 'Signing In...',
    theme: 'Theme',
    signOut: 'Sign Out',
    accountSettings: 'Account Settings',
    healthProfile: 'Health Profile'
  },
  te: {
    appName: 'మెడిఅసిస్ట్ AI',
    dashboard: 'డాష్‌బోర్డ్',
    myRecords: 'నా రికార్డులు',
    symptomChecker: 'లక్షణాల తనిఖీ',
    reportAnalyzer: 'నివేదిక విశ్లేషణ',
    imageAnalysis: 'చిత్ర విశ్లేషణ',
    chat: 'AI చాట్',
    emergency: 'అత్యవసరం',
    settings: 'సెట్టింగ్‌లు',
    disclaimer: 'MediAssist AI వృత్తిపరమైన వైద్య సలహాకు ప్రత్యామ్నాయం కాదు. ఎల్లప్పుడూ లైసెన్స్ పొందిన వైద్యుడిని సంప్రదించండి.',
    disclaimer_short: 'AI విశ్లేషణ మాత్రమే — రోగనిర్ధారణ కాదు',
    heroTitle: 'మీ AI ఆరోగ్య సహాయకుడు',
    heroSubtitle: 'లక్షణాలు, వైద్య నివేదికలు మరియు ఆరోగ్య ప్రశ్నలపై తక్షణ అంతర్దృష్టి పొందండి — అధునాతన AI శక్తితో.',
    getStarted: 'ప్రారంభించండి',
    learnMore: 'మరింత తెలుసుకోండి',
    patientsAssisted: 'సహాయం పొందిన రోగులు',
    reportsAnalyzed: 'విశ్లేషించబడిన నివేదికలు',
    aiAccuracy: 'AI విశ్లేషణ ఖచ్చితత్వం',
    languagesSupported: 'మద్దతు ఉన్న భాషలు',
    symptomCheckerTitle: 'AI లక్షణాల తనిఖీ',
    symptomCheckerDesc: 'తీవ్రత స్థాయిలు, ప్రమాద అంచనా మరియు వివరాల కోసం లక్షణాలను అందించండి.',
    reportAnalyzerTitle: 'నివేదిక విశ్లేషకం',
    reportAnalyzerDesc: 'రక్త పరీక్షలు లేదా ఇతర వైద్య నివేదికలను అప్‌లోడ్ చేయండి. AI సాంకేతిక పదాలను సులభతరం చేస్తుంది.',
    imageAnalysisTitle: 'చిత్ర విశ్లేషకం',
    imageAnalysisDesc: 'ప్రాథమిక విశ్లేషణ కోసం చర్మ సమస్యలు లేదా స్కాన్‌ల ఫోటోలను అప్‌లోడ్ చేయండి.',
    chatTitle: 'ఆరోగ్య చాట్‌బాట్',
    chatDesc: 'ఆరోగ్య సంబంధిత ప్రశ్నలు అడగండి, ఆహార సలహాలు పొందండి లేదా ఔషధాల సమాచారం తెలుసుకోండి.',
    symptomCheckerHeading: 'AI లక్షణాల అంచనా',
    symptomCheckerSub: 'మీ ఆరోగ్య లక్షణాలను స్పష్టంగా తెలపండి. AI క్లినికల్ పారామితులను తనిఖీ చేసి, తీవ్రతను లెక్కిస్తుంది.',
    describeSymptomsPlaceholder: 'మీ లక్షణాలను వివరించండి (ఉదా. తేలికపాటి తలనొప్పి, దగ్గు, నిన్నటి నుండి జ్వరం)...',
    analyzeSymptomsButton: 'లక్షణాలను విశ్లేషించండి',
    evaluatingSymptoms: 'లక్షణాలను విశ్లేషిస్తోంది. క్లినికల్ డేటాబేస్ తనిఖీ చేస్తోంది...',
    indicatedCondition: 'సూచించబడిన పరిస్థితి',
    clinicalExplanation: 'క్లినికల్ వివరణ',
    suggestedActions: 'సూచించబడిన చర్యలు',
    downloadPDF: 'PDF డౌన్‌లోడ్ చేయి',
    noAnalysisYet: 'ఇంకా విశ్లేషణ లేదు',
    noAnalysisYetDesc: 'అంచనా నివేదికలను పొందడానికి మీ లక్షణాలను పూరించి విశ్లేషించు క్లిక్ చేయండి.',
    reportAnalyzerHeading: 'వైద్య నివేదికల వివరణ',
    reportAnalyzerSub: 'ల్యాబ్ నివేదికలు, CBC లేదా ఇతర ఆరోగ్య పత్రాలను అప్‌లోడ్ చేయండి. AI అసహజ రీడింగులను గుర్తిస్తుంది.',
    dragDropPlaceholder: 'ఫైల్‌లను ఇక్కడ లాగి వదలండి, లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి (PDF, చిత్రాలు)',
    ocrScanning: 'ఫైల్ ప్రాసెస్ అవుతోంది. బయోమార్కర్లను సంగ్రహిస్తోంది...',
    parametersExtracted: 'సంగ్రహించిన ముఖ్య పారామితులు',
    simplifiedTranslation: 'సులభీకరించిన వివరణ',
    lifestyleAdvice: 'జీవనశైలి & పోషకాహార సలహాలు',
    tableParameter: 'పరామితి',
    tableValue: 'విలువ',
    tableNormal: 'సాధారణ పరిధి',
    tableStatus: 'స్థితి',
    uploadReportButton: 'నిвеదికను అప్‌లోడ్ చేయి',
    waitingForUpload: 'పత్రం కోసం వేచి ఉంది',
    waitingForUploadDesc: 'వివరమైన నివేదికలు మరియు హెచ్చరికలను పొందడానికి PDF లేదా స్కాన్ అప్‌లోడ్ చేయండి.',
    documentParsed: 'నివేదిక విజయవంతంగా విశ్లేషించబడింది',
    imageAnalysisHeading: 'దృశ్య నిర్ధారణ',
    imageAnalysisSub: 'చర్మ సమస్యలు, దద్దుర్లు లేదా స్కాన్‌ల ఫోటోలను అప్‌లోడ్ చేయండి. AI ఉపరితల మార్పులను గుర్తిస్తుంది.',
    visualScanCompleted: 'దృశ్య స్కాన్ పూర్తయింది',
    confidenceScore: 'AI మోడల్ విశ్వసనీయత స్కోరు',
    visualObservations: 'దృశ్య పరిశీలనలు',
    suggestionsActions: 'సూచించబడిన చర్యలు & తనిఖీలు',
    caveat: 'దృశ్య తనిఖీ మాత్రమే — ఇది పూర్తి వైద్య నిర్ధారణ కాదు.',
    clearFile: 'క్లియర్ చేయి',
    reAnalyze: 'తిరిగి విశ్లేషించు',
    awaitingPhoto: 'వైద్య ఫోటో కోసం వేచి ఉంది',
    awaitingPhotoDesc: 'విశ్వసనీయత స్కోరు మరియు ఫలితాలను పొందడానికి చర్మ ఫోటో లేదా స్కాన్ అప్‌లోడ్ చేయండి.',
    chatHeading: 'క్లినికల్ చాట్ సహాయకుడు',
    chatSub: 'జీవనశైలి, పోషకాహారం, వ్యాయామం లేదా సాధారణ ఔషధాల గురించి అడగండి.',
    suggestedQuestions: 'సూచించబడిన ప్రశ్నలు',
    typeMessagePlaceholder: 'ఆరోగ్యం గురించి ఏదైనా అడగండి...',
    sendButton: 'పంపు',
    typingIndicator: 'సమాధానాన్ని విశ్లేషిస్తోంది మరియు నిబంధనలను సేకరిస్తోంది...',
    emergencyWarning: '🚨 అత్యవసర హెచ్చరిక: తీవ్రమైన లక్షణాలు కనుగొనబడ్డాయి. వెంటనే అత్యవసర సేవలను సంప్రదించండి.',
    dashboardHeading: 'ఆరోగ్య నియంత్రణ డాష్‌బోర్డ్',
    dashboardSub: 'మీ ఆరోగ్యాన్ని పర్యవేక్షించండి, మునుపటి నివేదికలను సమీక్షించండి మరియు AI ఆరోగ్య చిట్కాలను పొందండి.',
    activeMinutes: 'యాక్టివ్ నిమిషాలు',
    heartRate: 'గుండె వేగం',
    healthScore: 'ఆరోగ్య సూచిక స్కోరు',
    riskStatus: 'వ్యవస్థాగత ప్రమాద స్థితి',
    recentActivity: 'ఇటీవలి కార్యాచరణ',
    recentActivityDesc: 'ఇటీవలి ఆరోగ్య పరీక్షలు మరియు విశ్లేషణ స్కాన్‌లు.',
    vitalTracker: 'యాక్టివిటీ & వైటల్స్ ట్రాకర్',
    activityLog: 'కన్సల్టేషన్లు & కార్యాచరణ లాగ్',
    noConsultations: 'ఇంకా ఎలాంటి సంప్రదింపులు నమోదు కాలేదు.',
    aiHealthTipTitle: 'AI ఆరోగ్య చిట్కాలు & సిఫారసులు',
    quickActions: 'త్వరిత నిర్ధారణ సాధనాలు',
    emergencyHeading: 'అత్యవసర సహాయం',
    emergencySub: 'మీకు గుండె నొప్పి, శ్వాస తీసుకోవడంలో తీవ్ర ఇబ్బంది లేదా రక్తస్రావం ఉంటే, వెంటనే అత్యవసర సేవలను సంప్రదించండి.',
    emergencyCall: 'అత్యవసర హాట్‌లైన్‌కు కాల్ చేయండి',
    emergencyContacts: 'అత్యవసర పరిచయాలు',
    loginHeading: 'తిరిగి స్వాగతం',
    loginSub: 'మీ MediAssist AI ఆరోగ్య సహాయకుడికి లాగిన్ చేయండి',
    emailLabel: 'ఇమెయిల్ చిరునామా',
    passwordLabel: 'పాస్‌వర్డ్',
    signInButton: 'సైన్ ఇన్',
    signingIn: 'సైన్ ఇన్ అవుతోంది...',
    theme: 'థీమ్',
    signOut: 'సైన్ అవుట్',
    accountSettings: 'ఖాతా సెట్టింగ్స్',
    healthProfile: 'ఆరోగ్య ప్రొఫైల్'
  },
  hi: {
    appName: 'मेडीअसिस्ट AI',
    dashboard: 'डैशबोर्ड',
    myRecords: 'मेरे रिकॉर्ड',
    symptomChecker: 'लक्षण जांच',
    reportAnalyzer: 'रिपोर्ट विश्लेषक',
    imageAnalysis: 'छवि विश्लेषण',
    chat: 'AI चैट',
    emergency: 'आपातकाल',
    settings: 'सेटिंग्स',
    disclaimer: 'MediAssist AI पेशेवर चिकित्सा सलाह का विकल्प नहीं है। हमेशा एक लाइसेंस प्राप्त स्वास्थ्य सेवा प्रदाता से परामर्श करें।',
    disclaimer_short: 'केवल AI विश्लेषण — कोई निदान नहीं',
    heroTitle: 'बुद्धिमान स्वास्थ्य सहायक',
    heroSubtitle: 'लक्षणों, चिकित्सा रिपोर्टों और स्वास्थ्य संबंधी प्रश्नों पर तुरंत जानकारी प्राप्त करें — उन्नत AI द्वारा संचालित।',
    getStarted: 'शुरू करें',
    learnMore: 'और जानें',
    patientsAssisted: 'सहायता प्राप्त मरीज',
    reportsAnalyzed: 'विश्लेषित रिपोर्टें',
    aiAccuracy: 'AI ट्राइएज सटीकता',
    languagesSupported: 'समर्थित भाषाएँ',
    symptomCheckerTitle: 'AI लक्षण जांचकर्ता',
    symptomCheckerDesc: 'गंभीरता के स्तर, जोखिम मूल्यांकन और विवरण की जांच करने के लिए वर्तमान लक्षण प्रदान करें।',
    reportAnalyzerTitle: 'रिपोर्ट विश्लेषक',
    reportAnalyzerDesc: 'ब्लड पैनल या अन्य मेडिकल रिपोर्ट अपलोड करें। AI जटिल चिकित्सा शब्दों को सरल बनाता है।',
    imageAnalysisTitle: 'छवि विश्लेषक',
    imageAnalysisDesc: 'प्रारंभिक दृश्य ट्राइएज के लिए त्वचा की स्थिति या स्कैन की तस्वीरें अपलोड करें।',
    chatTitle: 'स्वास्थ्य चैटबॉट',
    chatDesc: 'स्वास्थ्य संबंधी प्रश्न पूछें, आहार सुझाव मांगें, या दवा संबंधी सावधानियों की खोज करें।',
    symptomCheckerHeading: 'AI लक्षण मूल्यांकन',
    symptomCheckerSub: 'अपनी स्वास्थ्य संबंधी टिप्पणियों को स्पष्ट रूप से बताएं। AI नैदानिक मापदंडों की जांच करता है, आपातकालीन ट्रिगर को सचेत करता है, और गंभीरता की गणना करता है।',
    describeSymptomsPlaceholder: 'अपने लक्षणों का वर्णन करें (जैसे कि हल्का सिरदर्द, खाँसी, कल से बुखार)...',
    analyzeSymptomsButton: 'लक्षणों का विश्लेषण करें',
    evaluatingSymptoms: 'लक्षणों का मूल्यांकन किया जा रहा है। नैदानिक डेटाबेस की जाँच हो रही है...',
    indicatedCondition: 'इंगित स्थिति',
    clinicalExplanation: 'नैदानिक स्पष्टीकरण',
    suggestedActions: 'सुझाए गए कार्य',
    downloadPDF: 'PDF डाउनलोड करें',
    noAnalysisYet: 'अभी तक कोई विश्लेषण नहीं',
    noAnalysisYetDesc: 'मूल्यांकन रिपोर्ट तैयार करने के लिए अपने लक्षण भरें और विश्लेषण पर क्लिक करें।',
    reportAnalyzerHeading: 'मेडिकल रिपोर्ट स्पष्टीकरण',
    reportAnalyzerSub: 'लैब रिपोर्ट, CBC, थायराइड परीक्षण या अन्य स्वास्थ्य पत्रक अपलोड करें। AI क्षेत्रों को संसाधित करता है और असामान्य निष्कर्षों का विवरण देता है।',
    dragDropPlaceholder: 'फ़ाइलों को यहाँ खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें (PDF, चित्र)',
    ocrScanning: 'फ़ाइल संसाधित की जा रही है। बायोमार्कर निकाले जा रहे हैं...',
    parametersExtracted: 'निकाले गए प्रमुख मापदंड',
    simplifiedTranslation: 'सरलीकृत अनुवाद',
    lifestyleAdvice: 'जीवन शैली और पोषण संबंधी सलाह',
    tableParameter: 'पैरामीटर',
    tableValue: 'मूल्य',
    tableNormal: 'सामान्य सीमा',
    tableStatus: 'स्थिति',
    uploadReportButton: 'रिपोर्ट अपलोड करें',
    waitingForUpload: 'दस्तावेज़ की प्रतीक्षा है',
    waitingForUploadDesc: 'संरचित सारांश और चेतावनियों को स्वचालित रूप से देखने के लिए एक PDF या स्कैन अपलोड करें।',
    documentParsed: 'दस्तावेज़ सफलतापूर्वक पार्स किया गया',
    imageAnalysisHeading: 'दृश्य निदान',
    imageAnalysisSub: 'त्वचा की जलन, चकत्ते या स्कैन की तस्वीरें अपलोड करें। AI सतह की अनियमितताओं का पता लगाता है और विश्वास सूचकांक की गणना करता।',
    visualScanCompleted: 'दृश्य स्कैन पूरा हुआ',
    confidenceScore: 'AI मॉडल विश्वास स्कोर',
    visualObservations: 'दृश्य अवलोकन',
    suggestionsActions: 'सुझाए गए कार्य और जाँच',
    caveat: 'केवल दृश्य जांच — कोई ऑन्कोलॉजी या चिकित्सा नैदानिक जांच नहीं।',
    clearFile: 'फ़ाइल साफ़ करें',
    reAnalyze: 'छवि का पुनः विश्लेषण',
    awaitingPhoto: 'चिकित्सा फोटो की प्रतीक्षा है',
    awaitingPhotoDesc: 'विश्वास स्कोर, दृश्य निष्कर्ष और अलर्ट की समीक्षा करने के लिए त्वचा की फोटो या स्कैन अपलोड करें।',
    chatHeading: 'क्लिनिकल चैट साथी',
    chatSub: 'जीवन शैली, पोषण संबंधी सुझावों, व्यायाम, या सामान्य दवा निर्देशों के बारे में सामान्य प्रश्न पूछें।',
    suggestedQuestions: 'सुझाए गए प्रश्न',
    typeMessagePlaceholder: 'स्वास्थ्य या कल्याण संबंधी प्रश्न पूछें...',
    sendButton: 'भेजें',
    typingIndicator: 'क्वेरी का मूल्यांकन किया जा रहा है और नैदानिक दिशा-निर्देश संकलित किए जा रहे हैं...',
    emergencyWarning: '🚨 आपातकालीन चेतावनी: उच्च गंभीरता के लक्षण पाए गए हैं। तुरंत आपातकालीन प्रतिक्रिया से संपर्क करें।',
    dashboardHeading: 'स्वास्थ्य कमांड डैशबोर्ड',
    dashboardSub: 'महत्वपूर्ण संकेतों की निगरानी करें, पिछली परामर्शों की समीक्षा करें, और AI स्वास्थ्य युक्तियाँ प्राप्त करें।',
    activeMinutes: 'सक्रिय मिनट',
    heartRate: 'हृदय गति',
    healthScore: 'स्वास्थ्य सूचकांक स्कोर',
    riskStatus: 'प्रणालीगत जोखिम स्थिति',
    recentActivity: 'हाल की गतिविधि',
    recentActivityDesc: 'हाल ही में किए गए स्वास्थ्य परीक्षण और नैदानिक स्कैन।',
    vitalTracker: 'गतिविधि और महत्वपूर्ण संकेत ट्रैकर',
    activityLog: 'परामर्श और गतिविधि लॉग',
    noConsultations: 'अभी तक कोई परामर्श पंजीकृत नहीं है।',
    aiHealthTipTitle: 'AI स्वास्थ्य अंतर्दृष्टि और सिफारिशें',
    quickActions: 'त्वरित नैदानिक उपकरण',
    emergencyHeading: 'आपातकालीन सहायता',
    emergencySub: 'यदि आप सीने में दर्द, सांस लेने में गंभीर कठिनाई, या भारी रक्तस्राव का अनुभव कर रहे हैं, तो तुरंत स्थानीय आपातकालीन सेवाओं को कॉल करें।',
    emergencyCall: 'आपातकालीन हॉटलाइन कॉल करें',
    emergencyContacts: 'आपातकालीन संपर्क',
    loginHeading: 'वापसी पर स्वागत है',
    loginSub: 'अपने मेडीअसिस्ट AI स्वास्थ्य साथी में साइन इन करें',
    emailLabel: 'ईमेल पता',
    passwordLabel: 'पासवर्ड',
    signInButton: 'साइन इन',
    signingIn: 'साइन इन हो रहा है...',
    theme: 'थीम',
    signOut: 'साइन आउट',
    accountSettings: 'अकाउंट सेटिंग्स',
    healthProfile: 'स्वास्थ्य प्रोफाइल'
  },
  ta: {
    appName: 'மீடியாசிஸ்ட் AI',
    dashboard: 'டாஷ்போர்டு',
    myRecords: 'எனது ஆவணங்கள்',
    symptomChecker: 'அறிகுறி சரிபார்ப்பு',
    reportAnalyzer: 'அறிக்கை பகுப்பாய்வி',
    imageAnalysis: 'பட பகுப்பாய்வு',
    chat: 'AI அரட்டை',
    emergency: 'அவசரம்',
    settings: 'அமைப்புகள்',
    disclaimer: 'MediAssist AI என்பது தொழில்முறை மருத்துவ ஆலோசனைக்கு மாற்றாகாது. எப்போதும் உரிமம் பெற்ற மருத்துவரை அணுகவும்.',
    disclaimer_short: 'AI பகுப்பாய்வு மட்டுமே — நோய் கண்டறிதல் அல்ல',
    heroTitle: 'அறிவுசார் சுகாதார உதவியாளர்',
    heroSubtitle: 'அறிகுறிகள், மருத்துவ அறிக்கைகள் மற்றும் சுகாதார கேள்விகளுக்கு உடனடி நுண்ணறிவுகளைப் பெறுங்கள் — மேம்பட்ட AI மூலம்.',
    getStarted: 'தொடங்குங்கள்',
    learnMore: 'மேலும் அறிய',
    patientsAssisted: 'உதவி பெற்ற நோயாளிகள்',
    reportsAnalyzed: 'பகுப்பாய்வு செய்யப்பட்ட அறிக்கைகள்',
    aiAccuracy: 'AI பகுப்பாய்வு துல்லியம்',
    languagesSupported: 'ஆதரிக்கப்படும் மொழிகள்',
    symptomCheckerTitle: 'AI அறிகுறி சரிபார்ப்பான்',
    symptomCheckerDesc: 'தீவிரத்தன்மை, ஆபத்து மதிப்பீடு மற்றும் விவரங்களை சரிபார்க்க தற்போதைய அறிகுறிகளை வழங்கவும்.',
    reportAnalyzerTitle: 'அறிக்கை பகுப்பாய்வி',
    reportAnalyzerDesc: 'இரத்தப் பரிசோதனை அல்லது பிற மருத்துவ அறிக்கைகளைப் பதிவேற்றவும். AI கடினமான சொற்களை எளிதாக்குகிறது.',
    imageAnalysisTitle: 'பட பகுப்பாய்வி',
    imageAnalysisDesc: 'தொடக்க பகுப்பாய்விற்காக தோல் பிரச்சினைகள் அல்லது ஸ்கேன்களின் புகைப்படங்களைப் பதிவேற்றவும்.',
    chatTitle: 'சுகாதார அரட்டைப்பெட்டி',
    chatDesc: 'சுகாதாரம் தொடர்பான கேள்விகளைக் கேளுங்கள், உணவு ஆலோசனைகளைப் பெறுங்கள் அல்லது மருந்து முன்னெச்சரிக்கைகளைத் தேடுங்கள்.',
    symptomCheckerHeading: 'AI அறிகுறி மதிப்பீடு',
    symptomCheckerSub: 'உங்கள் சுகாதார அறிகுறிகளைத் தெளிவாகக் குறிப்பிடவும். AI மருத்துவ அளவீடுகளைச் சரிபார்த்து தீவிரத்தன்மையைக் கணக்கிடுகிறது.',
    describeSymptomsPlaceholder: 'உங்கள் அறிகுறிகளை விவரிக்கவும் (எ.கா. லேசான தலைவலி, இருமல், நேற்று முதல் காய்ச்சல்)...',
    analyzeSymptomsButton: 'அறிகுறிகளை பகுப்பாய்வு செய்',
    evaluatingSymptoms: 'அறிகுறிகள் பகுப்பாய்வு செய்யப்படுகின்றன. மருத்துவ தரவுத்தளம் சரிபார்க்கப்படுகிறது...',
    indicatedCondition: 'குறிப்பிடப்பட்ட நிலை',
    clinicalExplanation: 'மருத்துவ விளக்கம்',
    suggestedActions: 'பரிந்துரைக்கப்பட்ட நடவடிக்கைகள்',
    downloadPDF: 'PDF தரவிறக்கு',
    noAnalysisYet: 'இன்னும் பகுப்பாய்வு இல்லை',
    noAnalysisYetDesc: 'மதிப்பீட்டு அறிக்கைகளைப் பெற உங்கள் அறிகுறிகளைப் பூர்த்தி செய்து பகுப்பாய்வு செய் என்பதை அழுத்தவும்.',
    reportAnalyzerHeading: 'மருத்துவ அறிக்கை விளக்கவுரை',
    reportAnalyzerSub: 'ஆய்வக அறிக்கைகள், CBC அல்லது பிற சுகாதார தாள்களைப் பதிவேற்றவும். AI அசாதாரண முடிவுகளைக் கண்டறியும்.',
    dragDropPlaceholder: 'கோப்புகளை இங்கே இழுத்து விடுங்கள், அல்லது உலாவ கிளிக் செய்யவும் (PDF, படங்கள்)',
    ocrScanning: 'கோப்பு செயலாக்கப்படுகிறது. பயோமார்க்கர்களைப் பிரித்தெடுக்கிறது...',
    parametersExtracted: 'பிரித்தெடுக்கப்பட்ட முக்கிய அளவீடுகள்',
    simplifiedTranslation: 'எளிதாக்கப்பட்ட விளக்கம்',
    lifestyleAdvice: 'வாழ்க்கை முறை & ஊட்டச்சத்து ஆலோசனைகள்',
    tableParameter: 'அளவீடு',
    tableValue: 'மதிப்பு',
    tableNormal: 'சாதாரண வரம்பு',
    tableStatus: 'நிலை',
    uploadReportButton: 'அறிக்கையைப் பதிவேற்று',
    waitingForUpload: 'ஆவணத்திற்காக காத்திருக்கிறது',
    waitingForUploadDesc: 'விரிவான அறிக்கைகள் மற்றும் எச்சரிக்கைகளைத் தானாகக் காண PDF அல்லது ஸ்கேன் பதிவேற்றவும்.',
    documentParsed: 'அறிக்கை வெற்றிகரமாக பகுப்பாய்வு செய்யப்பட்டது',
    imageAnalysisHeading: 'காட்சி கண்டறிதல்',
    imageAnalysisSub: 'தோல் எரிச்சல், தடிப்புகள் அல்லது ஸ்கேன்களின் புகைப்படங்களைப் பதிவேற்றவும். AI மேற்பரப்பு மாற்றங்களைக் கண்டறியும்.',
    visualScanCompleted: 'காட்சி ஸ்கேன் முடிந்தது',
    confidenceScore: 'AI மாதிரியின் நம்பிக்கை மதிப்பெண்',
    visualObservations: 'காட்சி அவதானிப்புகள்',
    suggestionsActions: 'பரிந்துரைக்கப்பட்ட நடவடிக்கைகள் & சோதனைகள்',
    caveat: 'காட்சி சரிபார்ப்பு மட்டுமே — இது முழுமையான மருத்துவ கண்டறிதல் அல்ல.',
    clearFile: 'நீக்கு',
    reAnalyze: 'மீண்டும் பகுப்பாய்வு செய்',
    awaitingPhoto: 'மருத்துவ புகைப்படத்திற்காக காத்திருக்கிறது',
    awaitingPhotoDesc: 'நம்பிக்கை மதிப்பெண் மற்றும் முடிவுகளைப் பெற தோல் புகைப்படம் அல்லது ஸ்கேன் பதிவேற்றவும்.',
    chatHeading: 'மருத்துவ அரட்டை உதவியாளர்',
    chatSub: 'வாழ்க்கை முறை, ஊட்டச்சத்து, உடற்பயிற்சி அல்லது பொதுவான மருந்துகள் பற்றி கேளுங்கள்.',
    suggestedQuestions: 'பரிந்துரைக்கப்பட்ட கேள்விகள்',
    typeMessagePlaceholder: 'சுகாதாரம் குறித்து ஏதாவது கேளுங்கள்...',
    sendButton: 'அனுப்பு',
    typingIndicator: 'பதிலைப் பகுப்பாய்வு செய்கிறது மற்றும் விதிகளைச் சேகரிக்கிறது...',
    emergencyWarning: '🚨 அவசர எச்சரிக்கை: கடுமையான அறிகுறிகள் கண்டறியப்பட்டுள்ளன. உடனடியாக அவசர சேவைகளைத் தொடர்பு கொள்ளவும்.',
    dashboardHeading: 'சுகாதார கட்டுப்பாட்டு டாஷ்போர்டு',
    dashboardSub: 'உங்கள் ஆரோக்கியத்தைக் கண்காணிக்கவும், முந்தைய அறிக்கைகளை மதிப்பாய்வு செய்யவும், AI சுகாதார உதவிக்குறிப்புகளைப் பெறவும்.',
    activeMinutes: 'செயலில் உள்ள நிமிடங்கள்',
    heartRate: 'இதயத் துடிப்பு',
    healthScore: 'ஆரோக்கியக் குறியீடு மதிப்பெண்',
    riskStatus: 'முறையான ஆபத்து நிலை',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    recentActivityDesc: 'சமீபத்திய சுகாதார சோதனைகள் மற்றும் கண்டறியும் ஸ்கேன்கள்.',
    vitalTracker: 'செயல்பாடு & முக்கிய அளவீடுகள் கண்காணிப்பு',
    activityLog: 'ஆலோசனைகள் & செயல்பாட்டுப் பதிவு',
    noConsultations: 'இன்னும் ஆலோசனைகள் எதுவும் பதிவு செய்யப்படவில்லை.',
    aiHealthTipTitle: 'AI சுகாதார நுண்ணறிவு & பரிந்துரைகள்',
    quickActions: 'விரைவான கண்டறியும் கருவிகள்',
    emergencyHeading: 'அவசர உதவி',
    emergencySub: 'நெஞ்சு வலி, கடுமையான மூச்சுத்திணறல் அல்லது அதிக இரத்தப்போக்கு இருந்தால், உடனடியாக அவசர சேவைகளை அழைக்கவும்.',
    emergencyCall: 'அவசர உதவி எண்ணை அழைக்கவும்',
    emergencyContacts: 'அவசர தொடர்புகள்',
    loginHeading: 'மீண்டும் வருக',
    loginSub: 'உங்கள் மீடியாசிஸ்ட் AI சுகாதார உதவியாளரில் உள்நுழையவும்',
    emailLabel: 'மின்னஞ்சல் முகவரி',
    passwordLabel: 'கடவுச்சொல்',
    signInButton: 'உள்நுழையவும்',
    signingIn: 'உள்நுழைகிறது...',
    theme: 'தீம்',
    signOut: 'வெளியேறு',
    accountSettings: 'கணக்கு அமைப்புகள்',
    healthProfile: 'சுகாதார சுயவிவரம்'
  },
  kn: {
    appName: 'ಮೆಡಿಅಸಿಸ್ಟ್ AI',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    myRecords: 'ನನ್ನ ದಾಖಲೆಗಳು',
    symptomChecker: 'ಲಕ್ಷಣಗಳ ತಪಾಸಣೆ',
    reportAnalyzer: 'ವರದಿ ವಿಶ್ಲೇಷಕ',
    imageAnalysis: 'ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆ',
    chat: 'AI ಚಾಟ್',
    emergency: 'ತುರ್ತು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    disclaimer: 'MediAssist AI ವೃತ್ತಿಪರ ವೈದ್ಯಕೀಯ ಸಲಹೆಗೆ ಪರ್ಯಾಯವಲ್ಲ. ಯಾವಾಗಲೂ ಪರವಾನಗಿ ಪಡೆದ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    disclaimer_short: 'AI ವಿಶ್ಲೇಷಣೆ ಮಾತ್ರ — ರೋಗನಿರ್ಣಯವಲ್ಲ',
    heroTitle: 'ಬುದ್ಧಿವಂತ ಆರೋಗ್ಯ ಸಹಾಯಕ',
    heroSubtitle: 'ಲಕ್ಷಣಗಳು, ವೈದ್ಯಕೀಯ ವರದಿಗಳು ಮತ್ತು ಆರೋಗ್ಯ ಪ್ರಶ್ನೆಗಳ ಕುರಿತು ತತ್‌ಕ್ಷಣದ ಒಳನೋಟಗಳನ್ನು ಪಡೆಯಿರಿ — ಸುಧಾರಿತ AI ಮೂಲಕ.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    learnMore: 'ಹೆಚ್ಚು ತಿಳಿಯಿರಿ',
    patientsAssisted: 'ಸಹಾಯ ಪಡೆದ ರೋಗಿಗಳು',
    reportsAnalyzed: 'ವಿಶ್ಲೇಷಿಸಿದ ವರದಿಗಳು',
    aiAccuracy: 'AI ವಿಶ್ಲೇಷಣೆ ನಿಖರತೆ',
    languagesSupported: 'ಬೆಂಬಲಿತ ಭಾಷೆಗಳು',
    symptomCheckerTitle: 'AI ಲಕ್ಷಣಗಳ ತಪಾಸಕ',
    symptomCheckerDesc: 'ತೀವ್ರತೆಯ ಮಟ್ಟಗಳು, ಅಪಾಯದ ಮೌಲ್ಯಮಾಪನ ಮತ್ತು ವಿವರಗಳಿಗಾಗಿ ಲಕ್ಷಣಗಳನ್ನು ಒದಗಿಸಿ.',
    reportAnalyzerTitle: 'ವರದಿ ವಿಶ್ಲೇಷಕ',
    reportAnalyzerDesc: 'ರಕ್ತ ಪರೀಕ್ಷೆ ಅಥವಾ ಇತರ ವೈದ್ಯಕೀಯ ವರದಿಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. AI ತಾಂತ್ರಿಕ ಪದಗಳನ್ನು ಸರಳಗೊಳಿಸುತ್ತದೆ.',
    imageAnalysisTitle: 'ಚಿತ್ರ ವಿಶ್ಲೇಷಕ',
    imageAnalysisDesc: 'ಪ್ರಾಥಮಿಕ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಚರ್ಮದ ತೊಂದರೆಗಳು ಅಥವಾ ಸ್ಕ್ಯಾನ್‌ಗಳ ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    chatTitle: 'ಆರೋಗ್ಯ ಚಾಟ್‌ಬಾಟ್',
    chatDesc: 'ಆರೋಗ್ಯ ಸಂಬಂಧಿತ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ, ಆಹಾರ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ ಅಥವಾ ಔಷಧೀಯ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳನ್ನು ಹುಡುಕಿ.',
    symptomCheckerHeading: 'AI ಲಕ್ಷಣಗಳ ಮೌಲ್ಯಮಾಪನ',
    symptomCheckerSub: 'ನಿಮ್ಮ ಆರೋಗ್ಯದ ಲಕ್ಷಣಗಳನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ತಿಳಿಸಿ. AI ವೈದ್ಯಕೀಯ ನಿಯತಾಂಕಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ತೀವ್ರತೆಯನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡುತ್ತದೆ.',
    describeSymptomsPlaceholder: 'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ (ಉದಾ. ಸೌಮ್ಯ ತಲೆನೋವು, ಕೆಮ್ಮು, ನಿನ್ನೆಯಿಂದ ಜ್ವರ)...',
    analyzeSymptomsButton: 'ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    evaluatingSymptoms: 'ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ. ವೈದ್ಯಕೀಯ ಡೇಟಾಬೇಸ್ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    indicatedCondition: 'ಸೂಚಿಸಲಾದ ಸ್ಥಿತಿ',
    clinicalExplanation: 'ವೈದ್ಯಕೀಯ ವಿವರಣೆ',
    suggestedActions: 'ಸೂಚಿಸಲಾದ ಕ್ರಮಗಳು',
    downloadPDF: 'PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    noAnalysisYet: 'ಇನ್ನೂ ಯಾವುದೇ ವಿಶ್ಲೇಷಣೆ ಇಲ್ಲ',
    noAnalysisYetDesc: 'ಮೌಲ್ಯಮಾಪನ ವರದಿಗಳನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ ಮತ್ತು ವಿಶ್ಲೇಷಿಸಿ ಕ್ಲಿಕ್ ಮಾಡಿ.',
    reportAnalyzerHeading: 'ವೈದ್ಯಕೀಯ ವರದಿಗಳ ವಿವರಣೆ',
    reportAnalyzerSub: 'ಲ್ಯಾಬ್ ವರದಿಗಳು, CBC ಅಥವಾ ಇತರ ಆರೋಗ್ಯ ಪತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. AI ಅಸಹಜ ಫಲಿತಾಂಶಗಳನ್ನು ಗುರುತಿಸುತ್ತದೆ.',
    dragDropPlaceholder: 'ಫೈಲ್‌ಗಳನ್ನು ಇಲ್ಲಿಗೆ ಎಳೆದು ಬಿಡಿ, ಅಥವಾ ಬ್ರೌಸ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ (PDF, ಚಿತ್ರಗಳು)',
    ocrScanning: 'ಫೈಲ್ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ. ಬಯೋಮಾರ್ಕರ್‌ಗಳನ್ನು ಹೊರತೆಗೆಯಲಾಗುತ್ತಿದೆ...',
    parametersExtracted: 'ಹೊರತೆಗೆಯಲಾದ ಪ್ರಮುಖ ನಿಯತಾಂಕಗಳು',
    simplifiedTranslation: 'ಸರಳೀಕೃತ ವಿವರಣೆ',
    lifestyleAdvice: 'ಜೀವನಶೈಲಿ ಮತ್ತು ಪೌಷ್ಟಿಕಾಂಶದ ಸಲಹೆಗಳು',
    tableParameter: 'ನಿಯತಾಂಕ',
    tableValue: 'ಮೌಲ್ಯ',
    tableNormal: 'ಸಾಮಾನ್ಯ ಶ್ರೇಣಿ',
    tableStatus: 'ಸ್ಥಿತಿ',
    uploadReportButton: 'ವರದಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    waitingForUpload: 'ದಾಖಲೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
    waitingForUploadDesc: 'ವಿವರವಾದ ವರದಿಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ವೀಕ್ಷಿಸಲು PDF ಅಥವಾ ಸ್ಕ್ಯಾನ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    documentParsed: 'ವರದಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ವಿಶ್ಲೇಷಿಸಲಾಗಿದೆ',
    imageAnalysisHeading: 'ದೃಶ್ಯ ರೋಗನಿರ್ಣಯ',
    imageAnalysisSub: 'ಚರ್ಮದ ಕಿರಿಕಿರಿ, ದದ್ದುಗಳು ಅಥವಾ ಸ್ಕ್ಯಾನ್‌ಗಳ ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. AI ಮೇಲ್ಮೈ ಬದಲಾವಣೆಗಳನ್ನು ಗುರುತಿಸುತ್ತದೆ.',
    visualScanCompleted: 'ದೃಶ್ಯ ಸ್ಕ್ಯಾನ್ ಪೂರ್ಣಗೊಂಡಿದೆ',
    confidenceScore: 'AI ಮಾದರಿಯ ವಿಶ್ವಾಸಾರ್ಹತೆ ಸ್ಕೋರ್',
    visualObservations: 'ದೃಶ್ಯ ಅವಲೋಕನಗಳು',
    suggestionsActions: 'ಸೂಚಿಸಲಾದ ಕ್ರಮಗಳು ಮತ್ತು ಪರಿಶೀಲನೆಗಳು',
    caveat: 'ದೃಶ್ಯ ಪರಿಶೀಲನೆ ಮಾತ್ರ — ಇದು ಸಂಪೂರ್ಣ ವೈದ್ಯಕೀಯ ರೋಗನಿರ್ಣಯವಲ್ಲ.',
    clearFile: 'ಅಳಿಸಿ',
    reAnalyze: 'ಮತ್ತೆ ವಿಶ್ಲೇಷಿಸಿ',
    awaitingPhoto: 'ವೈದ್ಯಕೀಯ ಫೋಟೋಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
    awaitingPhotoDesc: 'ವಿಶ್ವಾಸಾರ್ಹತೆ ಸ್ಕೋರ್ ಮತ್ತು ಫಲಿತಾಂಶಗಳನ್ನು ಪಡೆಯಲು ಚರ್ಮದ ಫೋಟೋ ಅಥವಾ ಸ್ಕ್ಯಾನ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    chatHeading: 'ವೈದ್ಯಕೀಯ ಚಾಟ್ ಸಹಾಯಕ',
    chatSub: 'ಜೀವನಶೈಲಿ, ಪೌಷ್ಟಿಕಾಂಶ, ವ್ಯಾಯಾಮ ಅಥವಾ ಸಾಮಾನ್ಯ ಔಷಧಿಗಳ ಬಗ್ಗೆ ಕೇಳಿ.',
    suggestedQuestions: 'ಸೂಚಿಸಲಾದ ಪ್ರಶ್ನೆಗಳು',
    typeMessagePlaceholder: 'ಆರೋಗ್ಯದ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ...',
    sendButton: 'ಕಳುಹಿಸಿ',
    typingIndicator: 'ಉತ್ತರವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ ಮತ್ತು ನಿಯಮಗಳನ್ನು ಸಂಗ್ರಹಿಸಲಾಗುತ್ತಿದೆ...',
    emergencyWarning: '🚨 ತುರ್ತು ಎಚ್ಚರಿಕೆ: ತೀವ್ರ ಲಕ್ಷಣಗಳು ಕಂಡುಬಂದಿವೆ. ತಕ್ಷಣವೇ ತುರ್ತು ಸೇವೆಗಳನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    dashboardHeading: 'ಆರೋಗ್ಯ ನಿಯಂತ್ರಣ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    dashboardSub: 'ನಿಮ್ಮ ಆರೋಗ್ಯವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ, ಹಿಂದಿನ ವರದಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು AI ಆರೋಗ್ಯ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
    activeMinutes: 'ಸಕ್ರಿಯ ನಿಮಿಷಗಳು',
    heartRate: 'ಹೃದಯ ಬಡಿತ',
    healthScore: 'ಆರೋಗ್ಯ ಸೂಚ್ಯಂಕ ಸ್ಕೋರ್',
    riskStatus: 'ವ್ಯವಸ್ಥಿತ ಅಪಾಯದ ಸ್ಥಿತಿ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    recentActivityDesc: 'ಇತ್ತೀಚಿನ ಆರೋಗ್ಯ ತಪಾಸಣೆಗಳು ಮತ್ತು ರೋಗನಿರ್ಣಯದ ಸ್ಕ್ಯಾನ್‌ಗಳು.',
    vitalTracker: 'ಚಟುವಟಿಕೆ ಮತ್ತು ಪ್ರಮುಖ ನಿಯತಾಂಕಗಳ ಟ್ರ್ಯಾಕರ್',
    activityLog: 'ಸಮಾಲೋಚನೆಗಳು ಮತ್ತು ಚಟುವಟಿಕೆ ಲಾಗ್',
    noConsultations: 'ಇನ್ನೂ ಯಾವುದೇ ಸಮಾಲೋಚನೆಗಳು ನೋಂದಾಯಿಸಲ್ಪಟ್ಟಿಲ್ಲ.',
    aiHealthTipTitle: 'AI ಆರೋಗ್ಯ ಒಳನೋಟಗಳು ಮತ್ತು ಶಿಫಾರಸುಗಳು',
    quickActions: 'ತ್ವರಿತ ರೋಗನಿರ್ಣಯ ಸಾಧನಗಳು',
    emergencyHeading: 'ತುರ್ತು ಸಹಾಯ',
    emergencySub: 'ನಿಮಗೆ ಎದೆ ನೋವು, ತೀವ್ರ ಉಸಿರಾಟದ ತೊಂದರೆ ಅಥವಾ ವಿಪರೀತ ರಕ್ತಸ್ರಾವವಿದ್ದರೆ, ತಕ್ಷಣವೇ ಸ್ಥಳೀಯ ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಕರೆ ಮಾಡಿ.',
    emergencyCall: 'ತುರ್ತು ಸಹಾಯವಾಣಿಗೆ ಕರೆ ಮಾಡಿ',
    emergencyContacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    loginHeading: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    loginSub: 'ನಿಮ್ಮ ಮೆಡಿಅಸಿಸ್ಟ್ AI ಆರೋಗ್ಯ ಸಹಾಯಕರಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
    emailLabel: 'ಇಮೇಲ್ ವಿಳಾಸ',
    passwordLabel: 'ಪಾಸ್‌ವರ್ಡ್',
    signInButton: 'ಸೈನ್ ಇನ್',
    signingIn: 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    theme: 'ಥೀಮ್',
    signOut: 'ಸೈನ್ ಔಟ್',
    accountSettings: 'ಖಾತೆಯ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    healthProfile: 'ಆರೋಗ್ಯ ವಿವರ'
  },
  ml: {
    appName: 'മീഡിയസിസ്റ്റ് AI',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    myRecords: 'എന്റെ റെക്കോർഡുകൾ',
    symptomChecker: 'ലക്ഷണ പരിശോധന',
    reportAnalyzer: 'റിപ്പോർട്ട് വിശകലനം',
    imageAnalysis: 'ചിത്ര വിശകലനം',
    chat: 'AI ചാറ്റ്',
    emergency: 'അടിയന്തരാവസ്ഥ',
    settings: 'ക്രമീകരണങ്ങൾ',
    disclaimer: 'MediAssist AI പ്രൊഫഷണൽ മെഡിക്കൽ ഉപദേശത്തിന് പകരമല്ല. എപ്പോഴും ലൈസൻസുള്ള ഡോക്ടറെ സമീപിക്കുക.',
    disclaimer_short: 'AI വിശകലനം മാത്രം — രോഗനിർണയമല്ല',
    heroTitle: 'ബുദ്ധിമാനായ ആരോഗ്യ സഹായി',
    heroSubtitle: 'ലക്ഷണങ്ങൾ, മെഡിക്കൽ റിപ്പോർട്ടുകൾ, ആരോഗ്യ ചോദ്യങ്ങൾ എന്നിവയിൽ ഉടനടി വിവരങ്ങൾ നേടുക — വിപുലമായ AI വഴി.',
    getStarted: 'ആരംഭിക്കുക',
    learnMore: 'കൂടുതൽ അറിയുക',
    patientsAssisted: 'സഹായം ലഭിച്ച രോഗികൾ',
    reportsAnalyzed: 'വിശകലനം ചെയ്ത റിപ്പോർട്ടുകൾ',
    aiAccuracy: 'AI വിശകലന കൃത്യത',
    languagesSupported: 'പിന്തുണയ്ക്കുന്ന ഭാഷകൾ',
    symptomCheckerTitle: 'AI ലക്ഷണ പരിശോധകൻ',
    symptomCheckerDesc: 'തീവ്രത, അപകടസാധ്യത വിലയിരുത്തൽ, വിശദാംശങ്ങൾ എന്നിവ പരിശോധിക്കാൻ നിലവിലെ ലക്ഷണങ്ങൾ നൽകുക.',
    reportAnalyzerTitle: 'റിപ്പോർട്ട് വിശകലനകാരി',
    reportAnalyzerDesc: 'രക്തപരിശോധനയോ മറ്റ് മെഡിക്കൽ റിപ്പോർട്ടുകളോ അപ്‌ലോഡ് ചെയ്യുക. AI സാങ്കേതിക പദങ്ങൾ ലളിതമാക്കുന്നു.',
    imageAnalysisTitle: 'ചിത്ര വിശകലനകാരി',
    imageAnalysisDesc: 'പ്രാഥമിക വിശകലനത്തിനായി ചർമ്മ പ്രശ്നങ്ങളുടെയോ സ്കാനുകളുടെയോ ഫോട്ടോകൾ അപ്‌ലോഡ് ചെയ്യുക.',
    chatTitle: 'ആരോഗ്യ ചാറ്റ്ബോട്ട്',
    chatDesc: 'ആരോഗ്യ സംബന്ധിയായ ചോദ്യങ്ങൾ ചോദിക്കുക, ഭക്ഷണ നിർദ്ദേശങ്ങൾ നേടുക അല്ലെങ്കിൽ മരുന്ന് മുൻകരുതലുകൾ തിരയുക.',
    symptomCheckerHeading: 'AI ലക്ഷണ വിലയിരുത്തൽ',
    symptomCheckerSub: 'നിങ്ങളുടെ ആരോഗ്യ ലക്ഷണങ്ങൾ വ്യക്തമായി രേഖപ്പെടുത്തുക. AI ക്ലിനിക്കൽ പാരാമീറ്ററുകൾ പരിശോധിച്ച് തീവ്രത കണക്കാക്കുന്നു.',
    describeSymptomsPlaceholder: 'നിങ്ങളുടെ ലക്ഷണങ്ങൾ വിവരിക്കുക (ഉദാ. നേരിയ തലവേദന, ചുമ, ഇന്നലെ മുതൽ പനി)...',
    analyzeSymptomsButton: 'ലക്ഷണങ്ങൾ വിശകലനം ചെയ്യുക',
    evaluatingSymptoms: 'ലക്ഷണങ്ങൾ വിശകലനം ചെയ്യുന്നു. മെഡിക്കൽ ഡാറ്റാബേസ് പരിശോധിക്കുന്നു...',
    indicatedCondition: 'സൂചിപ്പിച്ച അവസ്ഥ',
    clinicalExplanation: 'ക്ലിനിക്കൽ വിശദീകരണം',
    suggestedActions: 'നിർദ്ദേശിച്ച നടപടികൾ',
    downloadPDF: 'PDF ഡൗൺലോഡ് ചെയ്യുക',
    noAnalysisYet: 'ഇതുവരെ വിശകലനം ലഭ്യമല്ല',
    noAnalysisYetDesc: 'വിലയിരുത്തൽ റിപ്പോർട്ടുകൾ ലഭിക്കുന്നതിന് നിങ്ങളുടെ ലക്ഷണങ്ങൾ നൽകി വിശകലനം ചെയ്യുക ക്ലിക്ക് ചെയ്യുക.',
    reportAnalyzerHeading: 'മെഡിക്കൽ റിപ്പോർട്ട് വിശദീകരണം',
    reportAnalyzerSub: 'ലാബ് റിപ്പോർട്ടുകൾ, CBC അല്ലെങ്കിൽ മറ്റ് ആരോഗ്യ രേഖകൾ അപ്‌ലോഡ് ചെയ്യുക. AI അസാധാരണമായ ഫലങ്ങൾ കണ്ടെത്തുന്നു.',
    dragDropPlaceholder: 'ഫയലുകൾ ഇവിടെ വലിച്ചിടുക, അല്ലെങ്കിൽ ബ്രൗസ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക (PDF, ചിത്രങ്ങൾ)',
    ocrScanning: 'ഫയൽ പ്രോസസ്സ് ചെയ്യുന്നു. ബയോമാർക്കറുകൾ വേർതിരിച്ചെടുക്കുന്നു...',
    parametersExtracted: 'വേർതിരിച്ചെടുത്ത പ്രധാന അളവുകൾ',
    simplifiedTranslation: 'ലളിതമാക്കിയ വിശദീകരണം',
    lifestyleAdvice: 'ജീവിതശൈലി & പോഷകാഹാര ഉപദേശങ്ങൾ',
    tableParameter: 'അളവ്',
    tableValue: 'മൂല്യം',
    tableNormal: 'സാധാരണ പരിധി',
    tableStatus: 'നില',
    uploadReportButton: 'റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക',
    waitingForUpload: 'രേഖയ്ക്കായി കാത്തിരിക്കുന്നു',
    waitingForUploadDesc: 'വിശദമായ റിപ്പോർട്ടുകളും മുന്നറിയിപ്പുകളും സ്വയമേവ കാണുന്നതിന് PDF അല്ലെങ്കിൽ സ്കാൻ അപ്‌ലോഡ് ചെയ്യുക.',
    documentParsed: 'റിപ്പോർട്ട് വിജയകരമായി വിശകലനം ചെയ്തു',
    imageAnalysisHeading: 'ദൃശ്യ രോഗനിർണ്ണയം',
    imageAnalysisSub: 'ചർമ്മത്തിലെ അസ്വസ്ഥതകൾ, തിണർപ്പുകൾ അല്ലെങ്കിൽ സ്കാനുകളുടെ ഫോട്ടോകൾ അപ്‌ലോഡ് ചെയ്യുക. AI ഉപരിതല വ്യത്യാസങ്ങൾ കണ്ടെത്തുന്നു.',
    visualScanCompleted: 'ദൃശ്യ സ്കാൻ പൂർത്തിയായി',
    confidenceScore: 'AI മോഡലിന്റെ വിശ്വാസ്യത സ്കോർ',
    visualObservations: 'ദൃശ്യ നിരീക്ഷണങ്ങൾ',
    suggestionsActions: 'നിർദ്ദേശിച്ച നടപടികളും പരിശോധനകളും',
    caveat: 'ദൃശ്യ പരിശോധന മാത്രം — ഇത് പൂർണ്ണമായ മെഡിക്കൽ രോഗനിർണ്ണയമല്ല.',
    clearFile: 'ഒഴിവാക്കുക',
    reAnalyze: 'വീണ്ടും വിശകലനം ചെയ്യുക',
    awaitingPhoto: 'മെഡിക്കൽ ഫോട്ടോയ്ക്കായി കാത്തിരിക്കുന്നു',
    awaitingPhotoDesc: 'വിശ്വാസ്യത സ്കോറും ഫലങ്ങളും ലഭിക്കുന്നതിന് ചർമ്മ ഫോട്ടോയോ സ്കാനോ അപ്‌ലോഡ് ചെയ്യുക.',
    chatHeading: 'മെഡിക്കൽ ചാറ്റ് സഹായി',
    chatSub: 'ജീവിതശൈലി, പോഷകാહારം, വ്യായാമം അല്ലെങ്കിൽ പൊതുവായ മരുന്നുകൾ എന്നിവയെക്കുറിച്ച് ചോദിക്കുക.',
    suggestedQuestions: 'നിർദ്ദേശിക്കപ്പെട്ട ചോദ്യങ്ങൾ',
    typeMessagePlaceholder: 'ആരോഗ്യത്തെക്കുറിച്ച് എന്തെങ്കിലും ചോദിക്കുക...',
    sendButton: 'അയക്കുക',
    typingIndicator: 'മറുപടി വിശകലനം ചെയ്യുന്നു, മാർഗ്ഗനിർദ്ദേശങ്ങൾ തയ്യാറാക്കുന്നു...',
    emergencyWarning: '🚨 അടിയന്തര മുന്നറിയിപ്പ്: ഗുരുതരമായ ലക്ഷണങ്ങൾ കണ്ടെത്തി. ഉടൻ തന്നെ അടിയന്തര സേവനങ്ങളുമായി ബന്ധപ്പെടുക.',
    dashboardHeading: 'ആരോഗ്യ നിയന്ത്രണ ഡാഷ്‌ബോർഡ്',
    dashboardSub: 'നിങ്ങളുടെ ആരോഗ്യം നിരീക്ഷിക്കുക, മുൻകാല റിപ്പോർട്ടുകൾ വിലയിരുത്തുക, AI ആരോഗ്യ നുറുങ്ങുകൾ നേടുക.',
    activeMinutes: 'സജീവ മിനിറ്റുകൾ',
    heartRate: 'ഹൃദയമിടിപ്പ്',
    healthScore: 'ആരോഗ്യ സൂചിക സ്കോർ',
    riskStatus: 'വ്യവസ്ഥാപിത അപകടസാധ്യത നില',
    recentActivity: 'സമീപകാല പ്രവർത്തനം',
    recentActivityDesc: 'സമീപകാല ആരോഗ്യ പരിശോധനകളും രോഗനിർണ്ണയ സ്കാനുകളും.',
    vitalTracker: 'പ്രവർത്തനവും പ്രധാന അളവുകളും നിരീക്ഷിക്കുന്ന ഉപകരണം',
    activityLog: 'കൺസൾട്ടേഷനുകളും പ്രവർത്തന ലോഗും',
    noConsultations: 'കൺസൾട്ടേഷനുകൾ ഒന്നും ഇതുവരെ രേഖപ്പെടുത്തിയിട്ടില്ല.',
    aiHealthTipTitle: 'AI ആരോഗ്യ ഉൾക്കാഴ്ചകളും ശുപാർശകളും',
    quickActions: 'ദ്രുത രോഗനിർണ്ണയ ഉപകരണങ്ങൾ',
    emergencyHeading: 'അടിയന്തര സഹായം',
    emergencySub: 'നിങ്ങൾക്ക് നെഞ്ചുവേദനയോ കടുത്ത ശ്വാസതടസ്സമോ കനത്ത രക്തസ്രാവമോ ഉണ്ടെങ്കിൽ ഉടൻ തന്നെ പ്രാദേശിക അടിയന്തര സേവനങ്ങളെ വിളിക്കുക.',
    emergencyCall: 'അടിയന്തര ഹോട്ട്ലൈൻ വിളിക്കുക',
    emergencyContacts: 'അടിയന്തര കോൺടാക്റ്റുകൾ',
    loginHeading: 'വീണ്ടും സ്വാഗതം',
    loginSub: 'നിങ്ങളുടെ മീഡിയസിസ്റ്റ് AI ആരോഗ്യ സഹായിയിലേക്ക് ലോഗിൻ ചെയ്യുക',
    emailLabel: 'ഇമെയിൽ വിലാസം',
    passwordLabel: 'പാസ്‌വേഡ്',
    signInButton: 'ലോഗിൻ ചെയ്യുക',
    signingIn: 'ലോഗിൻ ചെയ്യുന്നു...',
    theme: 'തീം',
    signOut: 'ലോഗ് ഔട്ട്',
    accountSettings: 'അക്കൗണ്ട് ക്രമീകരണങ്ങൾ',
    healthProfile: 'ആരോഗ്യ പ്രൊഫൈൽ'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('mediassist-lang') || 'en');

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('mediassist-lang', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
