import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { jsPDF } from 'jspdf';
import { useLanguage } from '../context/LanguageContext';
import { useEmergency } from '../context/EmergencyContext';
import { aiService, saveConsultation } from '../services/api';
import GlassCard from '../components/GlassCard';
import DisclaimerBanner from '../components/DisclaimerBanner';
import SeverityIndicator from '../components/SeverityIndicator';
import LoadingSpinner from '../components/LoadingSpinner';

import { Send, FileDown, Plus, HelpCircle, HeartHandshake } from 'lucide-react';

export default function SymptomChecker() {
  const { t } = useLanguage();
  const { checkForEmergency } = useEmergency();
  const [symptoms, setSymptoms] = useState('');
  const [loading, setLoading] = useState(false);
  const [analysisResult, setAnalysisResult] = useState(null);
  const [questionsHistory, setQuestionsHistory] = useState([]);

  const handleAnalyze = async (e) => {
    if (e) e.preventDefault();
    if (!symptoms.trim()) return;

    setLoading(true);
    setAnalysisResult(null);

    // Client-side emergency check
    checkForEmergency(symptoms);

    try {
      const result = await aiService.analyzeSymptoms(symptoms, questionsHistory);
      setAnalysisResult(result);

      // Save to dashboard consultation history
      saveConsultation({
        type: 'Symptom Check',
        summary: result.condition || 'General Analysis',
        severity: result.severity || 'medium',
        notes: `User symptoms: ${symptoms}. AI explanation: ${result.explanation}`
      });



    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };



  const downloadPDF = () => {
    if (!analysisResult) return;
    const doc = new jsPDF();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(14, 165, 233);
    doc.text('MediAssist AI Consultation Summary', 20, 20);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 28);

    doc.setDrawColor(200, 200, 200);
    doc.line(20, 32, 190, 32);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text('Reported Symptoms:', 20, 42);
    doc.setFont('helvetica', 'normal');
    doc.text(symptoms, 20, 48, { maxWidth: 170 });

    doc.setFont('helvetica', 'bold');
    doc.text('Assessment Condition:', 20, 68);
    doc.setFont('helvetica', 'normal');
    doc.text(analysisResult.condition || 'General Symptoms', 20, 74);

    doc.setFont('helvetica', 'bold');
    doc.text('Severity Indicator:', 20, 84);
    doc.setFont('helvetica', 'normal');
    doc.text((analysisResult.severity || 'moderate').toUpperCase(), 20, 90);

    doc.setFont('helvetica', 'bold');
    doc.text('Clinical Observations:', 20, 100);
    doc.setFont('helvetica', 'normal');
    doc.text(analysisResult.explanation || '', 20, 106, { maxWidth: 170 });

    doc.setFont('helvetica', 'bold');
    doc.text('Recommended Actions:', 20, 140);
    doc.setFont('helvetica', 'normal');
    doc.text(analysisResult.suggestions || '', 20, 146, { maxWidth: 170 });

    // Warning footer
    doc.setFillColor(245, 158, 11);
    doc.rect(20, 250, 170, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.text('DISCLAIMER: This report is generated by an AI assistant for health information purpose only.', 23, 258);
    doc.text('It does not replace professional diagnosis, treatment, or clinical assessment of a doctor.', 23, 264);

    doc.save('mediassist-consultation-summary.pdf');
  };

  const handleReset = () => {
    setSymptoms('');
    setAnalysisResult(null);
    setQuestionsHistory([]);
  };

  return (
    <div className="page-wrapper">
      <div className="section-container" style={{ paddingBottom: '80px' }}>
        
        {/* Banner safety warning */}
        <DisclaimerBanner style={{ marginBottom: '2rem' }} />

        <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '2rem' }} className="symptom-grid">
          
          {/* Input side */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
          >
            <GlassCard>
              <h2 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <HeartHandshake className="text-sky-400" /> AI Symptom Assessment
              </h2>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '1.5rem' }}>
                State your health observations clearly. The AI model checks for clinical parameters, alerts emergency triggers, and calculates severity levels.
              </p>

              <form onSubmit={handleAnalyze} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                <textarea
                    className="input-field"
                    placeholder="e.g. Mild headache, coughing, fever since yesterday..."
                    value={symptoms}
                    onChange={(e) => setSymptoms(e.target.value)}
                    style={{ height: '140px' }}
                    required
                  />

                <div style={{ display: 'flex', gap: '1rem', justifyContent: 'space-between', alignItems: 'center' }}>
                  <button type="button" onClick={handleReset} className="btn-ghost" style={{ padding: '0.6rem 1rem' }}>
                    <Plus size={16} /> New Check
                  </button>
                  <button type="submit" className="btn-primary" disabled={loading || !symptoms.trim()} style={{ padding: '0.6rem 1.5rem' }}>
                    {loading ? t('loading') : 'Analyze Symptoms'}
                    <Send size={16} />
                  </button>
                </div>
              </form>
            </GlassCard>
          </motion.div>

          {/* Results Side */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
          >
            {loading && (
              <GlassCard style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '300px' }}>
                <LoadingSpinner text="Evaluating symptoms. Cross-referencing database..." />
              </GlassCard>
            )}

            {!loading && !analysisResult && (
              <GlassCard style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '300px', color: 'var(--text-secondary)', textAlign: 'center' }}>
                <HelpCircle size={48} className="text-slate-500 mb-3 animate-float" />
                <h3 style={{ fontWeight: 600, fontSize: '1.1rem', marginBottom: '0.25rem' }}>No Analysis Yet</h3>
                <p style={{ fontSize: '0.85rem', maxWidth: '300px' }}>
                  Fill in your symptoms and click analyze to start generating assessment reports.
                </p>
              </GlassCard>
            )}

            {!loading && analysisResult && (
              <GlassCard style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <h3 style={{ fontSize: '1.25rem', fontWeight: 800 }}>Preliminary Assessment</h3>
                  <button onClick={downloadPDF} className="btn-ghost" style={{ padding: '0.4rem 0.8rem', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
                    <FileDown size={14} /> Download PDF
                  </button>
                </div>

                <SeverityIndicator level={analysisResult.severity} />

                <div>
                  <h4 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', fontWeight: 600, marginBottom: '0.25rem' }}>
                    Indicated Condition:
                  </h4>
                  <p style={{ fontSize: '1.1rem', fontWeight: 700, margin: 0, color: 'var(--color-primary)' }}>
                    {analysisResult.condition}
                  </p>
                </div>

                <div>
                  <h4 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', fontWeight: 600, marginBottom: '0.25rem' }}>
                    Clinical Explanation:
                  </h4>
                  <p style={{ fontSize: '0.9rem', margin: 0, color: 'var(--text-primary)' }}>
                    {analysisResult.explanation}
                  </p>
                </div>

                <div>
                  <h4 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', fontWeight: 600, marginBottom: '0.25rem' }}>
                    Suggested Actions:
                  </h4>
                  <p style={{ fontSize: '0.9rem', margin: 0, color: 'var(--text-primary)' }}>
                    {analysisResult.suggestions}
                  </p>
                </div>

                <div style={{ borderTop: '1px solid var(--border-glass)', paddingTop: '1rem', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                  ⚠️ Preliminary AI assessment only. If symptoms persist or escalate, seek guidance from a licensed clinical practitioner.
                </div>
              </GlassCard>
            )}
          </motion.div>

        </div>

      </div>

      <style>{`
        .symptom-grid {
          grid-template-columns: 1fr;
        }
        @media (min-width: 1024px) {
          .symptom-grid {
            grid-template-columns: 1fr 1fr;
          }
        }
      `}</style>
    </div>
  );
}
